server:
  port: 8089

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2



  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

    show-sql: true
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 50
          order_inserts: true

jwt:
  key:
    alias: weihong
    password: lanweihong
    storepass: lanweihong
    path: jwt.jks
debug: false